name: Build and deploy Vite React app to Azure Web App - Rentease-frontendsy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Fix permission issue for Vite
      - name: Fix Vite permission
        run: chmod +x node_modules/.bin/vite

      # Build project
      - name: Build project
        run: npm run build

      # Upload dist folder
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download dist
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      # Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Rentease-frontendsy'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist
